In [2]:
import numpy as np

In [37]:
A = np.array([[-11,-10,5],[5,4,-5],[-20,-20,4]])
eigen_values, eigen_vectors = np.linalg.eig(A)
print("eigen values = \n", eigen_values)

eigen_vectors = np.round(eigen_vectors,3)
for i in range(3):
    eigen_vectors[:,i] = eigen_vectors[:,i]/(min(eigen_vectors[:,i][eigen_vectors[:,i] != 0]))
print("eigen values = \n", eigen_vectors)

eigen values = 
 [ 4. -1. -6.]
eigen values = 
 [[-1.  1.  0.]
 [ 1. -1.  1.]
 [-1.  0.  2.]]


In [77]:
#power method
u = np.array([[1],[1],[1]])
for j in range(60):
    v = A @ u
    u = v
    u = np.round(u,3)
    u = u/min(u[u!=0])
print("eigen vector = \n",u)

Lambda1 = np.round(((u.T @ A @ u)/np.sum(np.square(u))))[0][0]
print("eigen value =",Lambda1)

eigen vector = 
 [[-0. ]
 [ 0.5]
 [ 1. ]]
eigen value = -6.0


In [80]:
#power method
temp_A = A - Lambda1*np.identity(3)
u = np.array([[1],[1],[1]])
for j in range(100):
    v = temp_A @ u
    u = v
    u = np.round(u,3)
    u = u/min(u[u!=0])
print("eigen vector = \n",u)

Lambda2 = np.round(((u.T @ temp_A @ u)/np.sum(np.square(u))))[0][0] + Lambda1 
print("eigen value =", Lambda2)


eigen vector = 
 [[-1.]
 [ 1.]
 [-1.]]
eigen value = 4.0


In [87]:
# inverse power method
temp_lambda = 1
temp_A2 = A - temp_lambda*np.identity(3)
u = np.array([[1],[1],[1]])
for j in range(100):
    v = np.linalg.inv(temp_A2) @ u
    u = v
    u = np.round(u,3)
    u = u/min(u[u!=0])

u = np.round(u,1)
print("eigen vector = \n",u)

Lambda2 = np.round(((u.T @ A @ u)/np.sum(np.square(u))))[0][0]
print("eigen value =", Lambda2)

eigen vector = 
 [[ 1.]
 [-1.]
 [-0.]]
eigen value = -1.0
